-- REF [ADM VENDAS] 288 PEDIDOS FORNEC PACOTES 

WITH SETOR AS (SELECT ZOCODIGO,ZODESCRICAO FROM ZONA),

ENDE AS (SELECT CLICODIGO, ZODESCRICAO FROM ENDCLI INNER JOIN SETOR ON ENDCLI.ZOCODIGO=SETOR.ZOCODIGO WHERE ENDFAT='S'),



CLI AS (SELECT  CLIEN.CLICODIGO,CLIRAZSOCIAL,ZODESCRICAO FROM CLIEN LEFT JOIN ENDE ON CLIEN.CLICODIGO=ENDE.CLICODIGO ),

PROD AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU),

CLIPCT AS (SELECT PCTCLI.CLICODIGO,CLIRAZSOCIAL,ZODESCRICAO SETOR_COMERCIAL,PCTNUMERO,PCTDTCAD,PCTDTFIM,PCTDTSUSP,PCTOBSER,PCTSUSPOBS FROM PCTCLI
           LEFT JOIN CLI ON PCTCLI.CLICODIGO=CLI.CLICODIGO WHERE PCTSITUACAO<>'C')

SELECT CLICODIGO,
        CLIRAZSOCIAL RAZAO_SOCIAL,
         SETOR_COMERCIAL, 
           PCTPRO.PCTNUMERO,
             PCTDTCAD PCT_DATA_CADASTRO,
              PCTDTFIM TERMINO,PCTPRO.PROCODIGO,
                 PRODESCRICAO DESCRICAO,
                  CAST (PCPPCOUNIT AS NUMERIC(15,5)) PRECO_UNIT,
                    PCPQTDADE QTD,
                     PCPSALDO SALDO_ATUAL,
                      PCTDTSUSP DATA_SUSPENSAO,
                        CAST(PCTOBSER AS VARCHAR(500)) OBS,
                          PCTSUSPOBS,
                           (CAST (PCPPCOUNIT AS NUMERIC(15,5))*PCPQTDADE) VALORTOTAL,
                             EXTRACT(YEAR FROM PCTDTCAD) ANO
                           FROM PCTPRO 
                             INNER JOIN CLIPCT ON PCTPRO.PCTNUMERO=CLIPCT.PCTNUMERO
                               LEFT JOIN PROD ON PCTPRO.PROCODIGO=PROD.PROCODIGO